/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 */
import { delay, http, HttpResponse } from "msw"

export const getGetStringByStringMockHandler = () => {
  return http.get("*/cats/:id", async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    })
  })
}
export const getDefaultMock = () => [getGetStringByStringMockHandler()]
